version: 0.2

phases:
    install:
        # We're going to do something real stupid here until I decide how to deal with the template and code pipeline's inability to understand submodules
        commands:
            - curl https://github.com/jessiepuls/simple-hugo-theme/archive/master.zip output simple-hugo-theme.zip
            - cp -r simple-hugo-theme-master/* site/themes/simple-hugo-theme/
    build:
        commands:
            - echo "Building site"
            - cd site
            - hugo
            - echo "S3 Upload Beginning"
            - aws s3 sync public/ s3://www.jessie.wtf/ --region us-east-1 --delete --acl public-read
            - echo "S3 Upload Complete"

    post_build:
        commands:
            - echo "Build complete"
#            - aws sns publish --topic-arn YOUR_TOPIC_ARN --subject 'AWS CodeBuild Complete' --message 'Your build using AWS CodeBuild has been completed. Check the CodeBuild console to see the details.'