baseURL = "/"
author = "Jessie Puls"
title = "Making a test thing"
theme = "simple-hugo-theme"
languageCode = "en-us"

enableRobotsTXT = true
SectionPagesMenu = ["main", "social"]

# [params.meta]
# description = "Hugo and Foundation mobile enabled theme."
# keywords = "foundation6, hugo, responsive, theme, mobile, developer"

[params.header]
headertitle = "Hello!"
headerdescription = "Please click buttons. They do nothing."

[[params.header.button]]
text = "Todo"
href = "/todo"

[[params.header.button]]
text = "This could probably go somewhere"
href = ""

[[params.main.module]]
title = "Some content module"
body = "Stuff Stuff Stuff Stuff Stuff Stuff Stuff Stuff Stuff Stuff Stuff Stuff Stuff Stuff Stuff Stuff Stuff Stuff Stuff Stuff Stuff Stuff Stuff Stuff Stuff Stuff Stuff Stuff Stuff Stuff"

[[params.main.module]]
title = "Some other content module"
body = "Other Stuff Other Stuff Other Stuff Other Stuff Other Stuff Other Stuff Other Stuff Other Stuff Other Stuff Other Stuff Other Stuff Other Stuff"

[params.footer]
email = "jessiepuls@gmail.com"

[[menu.main]]
name = "Blog"
url = "/blog"

[[menu.main]]
name = "Contact"
url = "/contact"

[[menu.social]]
name = "Twitter"
url = "http://twitter.com/jessiepuls"

[[menu.social]]
name = "LinkedIn"
url = "https://www.linkedin.com/in/jessiepuls/"

